import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the source files.
*/
`;

const prod = (process.argv[2] === "production");

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...["fs", "os", "path"].map(x => `node:${x}`)
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
}).then(() => {
	console.log("Build complete.");
	const vaultPluginDir = "C:/Users/tim_g/OneDrive/Documents/postal/.obsidian/plugins/obsidian-denokv-publisher";
	fs.mkdirSync(vaultPluginDir, { recursive: true });
	fs.copyFileSync("main.js", path.join(vaultPluginDir, "main.js"));
	fs.copyFileSync("manifest.json", path.join(vaultPluginDir, "manifest.json"));
	console.log("Successfully copied main.js and manifest.json to Obsidian vault!");
}).catch(() => process.exit(1));
