/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the source files.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DenoKVPublisherPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  endpointUrl: "",
  authToken: "",
  publishedNotes: {}
};
var DenoKVPublisherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "LOJU Settings" });
    new import_obsidian.Setting(containerEl).setName("Endpoint URL").setDesc("The HTTP URL to ingest your notes (e.g. your LOJU app endpoint)").addText(
      (text) => text.setPlaceholder("https://loju.ca/api/ingest").setValue(this.plugin.settings.endpointUrl).onChange(async (value) => {
        this.plugin.settings.endpointUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Authorization Token").setDesc("The bearer token required to authenticate with your LOJU server").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("Enter auth token").setValue(this.plugin.settings.authToken).onChange(async (value) => {
        this.plugin.settings.authToken = value.trim();
        await this.plugin.saveSettings();
      });
    });
    const advancedDetails = containerEl.createEl("details");
    advancedDetails.style.marginTop = "2rem";
    advancedDetails.style.padding = "1rem";
    advancedDetails.style.border = "1px solid var(--background-modifier-border)";
    advancedDetails.style.borderRadius = "6px";
    advancedDetails.style.backgroundColor = "var(--background-secondary)";
    const advancedSummary = advancedDetails.createEl("summary", { text: "Advanced Settings & Troubleshooting" });
    advancedSummary.style.cursor = "pointer";
    advancedSummary.style.fontWeight = "600";
    advancedSummary.style.color = "var(--text-muted)";
    advancedSummary.style.outline = "none";
    const advancedContainer = advancedDetails.createEl("div");
    advancedContainer.style.marginTop = "1rem";
    const numPublished = Object.keys(this.plugin.settings.publishedNotes).length;
    new import_obsidian.Setting(advancedContainer).setName("Tracked Notes").setDesc(`Currently publishing ${numPublished} note(s).`).addButton((btn) => {
      btn.setButtonText("Clear Local Tracking Cache").setWarning().setTooltip("This forgets which notes were published locally. It does not delete notes on LOJU.").onClick(async () => {
        if (confirm("Are you sure you want to clear the local tracking cache? The next publish will re-upload all publish:true notes.")) {
          this.plugin.settings.publishedNotes = {};
          await this.plugin.saveSettings();
          this.display();
        }
      });
    });
    new import_obsidian.Setting(advancedContainer).setName("Wipe Remote LOJU Database").setDesc("Deletes all notes currently stored in the remote LOJU database and clears local tracking cache.").addButton((btn) => {
      btn.setButtonText("Wipe Database").setWarning().setTooltip("Destructive action. Wipes the remote LOJU database.").onClick(async () => {
        if (confirm("WARNING: Are you sure you want to wipe the remote LOJU database? This will permanently delete all published notes from the server.")) {
          await this.plugin.publisher.wipeAll();
          this.display();
        }
      });
    });
    const footerEl = containerEl.createEl("div", { cls: "loju-settings-footer" });
    footerEl.style.marginTop = "3rem";
    footerEl.style.textAlign = "center";
    footerEl.style.fontSize = "0.9em";
    footerEl.style.color = "var(--text-muted)";
    footerEl.createEl("span", { text: "\u{1F347} Thank you!" });
  }
};

// src/publisher.ts
var import_obsidian2 = require("obsidian");
var DenoKVPublisher = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  async publishAll() {
    const { settings } = this.plugin;
    if (!settings.endpointUrl) {
      new import_obsidian2.Notice("LOJU: Please configure your Endpoint URL in the settings.");
      return;
    }
    new import_obsidian2.Notice("Checking notes for updates...");
    const allFiles = this.plugin.app.vault.getMarkdownFiles();
    const currentVaultPaths = new Set(allFiles.map((f) => f.path));
    const toPublish = [];
    const toUnpublish = [];
    for (const file of allFiles) {
      const cache = this.plugin.app.metadataCache.getFileCache(file);
      const frontmatter = cache?.frontmatter;
      const pubVal = frontmatter?.publish;
      const isPublishEnabled = pubVal === true || pubVal === "true" || pubVal === 1 || pubVal === "yes" || Array.isArray(pubVal) && (pubVal.includes("true") || pubVal.includes(true) || pubVal.includes("yes"));
      const tracked = settings.publishedNotes[file.path];
      if (isPublishEnabled) {
        const isNew = !tracked;
        const isModified = tracked && file.stat.mtime > tracked.mtime;
        if (isNew || isModified) {
          toPublish.push(file);
        }
      } else {
        if (tracked) {
          toUnpublish.push({
            path: file.path,
            title: tracked.title || file.basename
          });
        }
      }
    }
    for (const path of Object.keys(settings.publishedNotes)) {
      if (!currentVaultPaths.has(path)) {
        const tracked = settings.publishedNotes[path];
        toUnpublish.push({
          path,
          title: tracked.title || ""
        });
      }
    }
    const totalTasks = toPublish.length + toUnpublish.length;
    if (totalTasks === 0) {
      new import_obsidian2.Notice("LOJU: Everything is up to date!");
      return;
    }
    new import_obsidian2.Notice(`Syncing ${totalTasks} change(s) to LOJU...`);
    let successPublishCount = 0;
    let successUnpublishCount = 0;
    let errorCount = 0;
    const authHeader = settings.authToken ? `Bearer ${settings.authToken}` : "";
    for (const note of toUnpublish) {
      try {
        const response = await (0, import_obsidian2.requestUrl)({
          url: settings.endpointUrl,
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": authHeader
          },
          body: JSON.stringify({
            action: "unpublish",
            path: note.path,
            title: note.title
          })
        });
        if (response.status >= 200 && response.status < 300) {
          delete settings.publishedNotes[note.path];
          successUnpublishCount++;
        } else {
          console.error(`Failed to unpublish ${note.path}: status ${response.status}`, response.text);
          errorCount++;
        }
      } catch (err) {
        console.error(`Error unpublishing ${note.path}:`, err);
        errorCount++;
      }
    }
    for (const file of toPublish) {
      try {
        let cache = this.plugin.app.metadataCache.getFileCache(file);
        let frontmatter = cache ? { ...cache.frontmatter } : {};
        let firstPublishedVal = frontmatter.first_published;
        let mtime = file.stat.mtime;
        if (!firstPublishedVal) {
          firstPublishedVal = (/* @__PURE__ */ new Date()).toISOString();
          await this.plugin.app.fileManager.processFrontMatter(file, (fm) => {
            if (!fm.first_published) {
              fm.first_published = firstPublishedVal;
            }
          });
          await new Promise((resolve) => setTimeout(resolve, 100));
          const nextCache = this.plugin.app.metadataCache.getFileCache(file);
          if (nextCache) {
            cache = nextCache;
            frontmatter = { ...nextCache.frontmatter };
          }
          frontmatter.first_published = firstPublishedVal;
          mtime = file.stat.mtime;
        }
        const content = await this.plugin.app.vault.read(file);
        const tags = cache ? (0, import_obsidian2.getAllTags)(cache) || [] : [];
        const cleanTags = tags.map((t) => t.replace(/^#/, ""));
        const payload = {
          action: "publish",
          path: file.path,
          title: file.basename,
          content,
          frontmatter,
          tags: cleanTags,
          mtime,
          ctime: file.stat.ctime
        };
        const response = await (0, import_obsidian2.requestUrl)({
          url: settings.endpointUrl,
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "Authorization": authHeader
          },
          body: JSON.stringify(payload)
        });
        if (response.status >= 200 && response.status < 300) {
          settings.publishedNotes[file.path] = {
            path: file.path,
            title: file.basename,
            mtime
          };
          successPublishCount++;
        } else {
          console.error(`Failed to publish ${file.path}: status ${response.status}`, response.text);
          errorCount++;
        }
      } catch (err) {
        console.error(`Error publishing ${file.path}:`, err);
        errorCount++;
      }
    }
    await this.plugin.saveSettings();
    if (errorCount === 0) {
      new import_obsidian2.Notice(
        `LOJU Sync Success!
Published/Updated: ${successPublishCount}
Unpublished: ${successUnpublishCount}`
      );
    } else {
      new import_obsidian2.Notice(
        `LOJU Sync completed with ${errorCount} error(s).
Succeeded: ${successPublishCount + successUnpublishCount}
Failed: ${errorCount}`
      );
    }
  }
  async wipeAll() {
    const { settings } = this.plugin;
    if (!settings.endpointUrl) {
      new import_obsidian2.Notice("LOJU: Please configure your Endpoint URL in the settings.");
      return;
    }
    new import_obsidian2.Notice("Wiping remote LOJU database...");
    const authHeader = settings.authToken ? `Bearer ${settings.authToken}` : "";
    try {
      const response = await (0, import_obsidian2.requestUrl)({
        url: settings.endpointUrl,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": authHeader
        },
        body: JSON.stringify({
          action: "wipe"
        })
      });
      if (response.status >= 200 && response.status < 300) {
        settings.publishedNotes = {};
        await this.plugin.saveSettings();
        new import_obsidian2.Notice("Remote LOJU database wiped successfully and local published cache cleared.");
      } else {
        console.error("Failed to wipe remote LOJU database:", response.status, response.text);
        new import_obsidian2.Notice(`Wipe failed: remote server returned status ${response.status}`);
      }
    } catch (err) {
      console.error("Error during remote LOJU database wipe:", err);
      new import_obsidian2.Notice(`Wipe failed: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
};

// src/main.ts
var DenoKVPublisherPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    console.log("Loading LOJU Plugin");
    await this.loadSettings();
    this.publisher = new DenoKVPublisher(this);
    const ribbonIconEl = this.addRibbonIcon("share-2", "Send to LOJU", async () => {
      await this.publisher.publishAll();
    });
    ribbonIconEl.empty();
    ribbonIconEl.createSpan({ text: "\u{1F347}", cls: "loju-ribbon-grape" });
    ribbonIconEl.addClass("loju-publisher-ribbon-class");
    this.addCommand({
      id: "send-to-loju",
      name: "Send to LOJU",
      callback: async () => {
        await this.publisher.publishAll();
      }
    });
    this.addCommand({
      id: "wipe-loju",
      name: "Wipe remote LOJU database",
      callback: async () => {
        if (confirm("WARNING: Are you sure you want to wipe the remote LOJU database? This will permanently delete all published notes from the server.")) {
          await this.publisher.wipeAll();
        }
      }
    });
    this.addSettingTab(new DenoKVPublisherSettingTab(this.app, this));
  }
  onunload() {
    console.log("Unloading LOJU Plugin");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
